# Collection with code quality jobs that run npm scripts

include:
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.0/jobs/Npm-Lint-Css.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.0/jobs/Npm-Lint-Html.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.0/jobs/Npm-Lint-Js.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.0/jobs/Npm-Lint-Md.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.0/jobs/Npm-Lint-Prettier.gitlab-ci.yml
