# Base with common pipeline elements for all container collections

include:
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.30/templates/Container.gitlab-ci.yml
  - template: Container-Scanning.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.30/jobs/Container-Remove-Image.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.30/jobs/Docker-Dive.gitlab-ci.yml

variables:
  TEMP_IMAGE_REPOSITORY: $CI_REGISTRY_IMAGE/tmp
  TEMP_IMAGE_TAG: $CI_PIPELINE_ID

# Includes updates for image:tag and to run in container-test
container_scanning:
  variables:
    # Override repository for temp image and tag.  Must be done in job since defined in job template.
    CI_IMAGE_FULL_NAME: $TEMP_IMAGE_REPOSITORY
    CI_IMAGE_IDENTITY_TAG: $TEMP_IMAGE_TAG
  stage: container-test
  rules:
    - if: $CONTAINER_SCANNING_DISABLED == 'true' || $CONTAINER_SCANNING_DISABLED == '1'
      when: never
    - if: |
        ($CI_COMMIT_BRANCH || $CI_COMMIT_TAG || $CI_MERGE_REQUEST_IID) &&
        $CI_GITLAB_FIPS_MODE == "true" &&
        $CS_ANALYZER_IMAGE !~ /-(fips|ubi)\z/
      variables:
        CS_IMAGE_SUFFIX: -fips
    - if: $CI_COMMIT_BRANCH || $CI_COMMIT_TAG || $CI_MERGE_REQUEST_IID

# Included from Docker-Dive.gitlab-ci.yml
docker_dive:
  variables:
    # Override repository for temp image and tag.  Must be done in job since defined in job template.
    CI_IMAGE_FULL_NAME: $TEMP_IMAGE_REPOSITORY
    CI_IMAGE_IDENTITY_TAG: $TEMP_IMAGE_TAG

# Included from Container-Remove-Image.gitlab-ci.yml
remove_image:
  variables:
    # Override repository for temp image and tag.  Must be done in job since defined in job template.
    CI_IMAGE_FULL_NAME: $TEMP_IMAGE_REPOSITORY
    CI_IMAGE_IDENTITY_TAG: $TEMP_IMAGE_TAG
