# Collection to consolidate Docker build, lint, scan, and deploy.

include:
  - local: /collections/Container-Base.gitlab-ci.yml
  - local: /jobs/Docker-Build.gitlab-ci.yml
  - local: /jobs/Docker-Deploy.gitlab-ci.yml

# Included from Docker-Build.gitlab-ci.yml
docker_build:
  variables:
    # Override repository for temp image and tag.  Must be done in job since defined in job template.
    CI_IMAGE_FULL_NAME: $TEMP_IMAGE_REPOSITORY
    CI_IMAGE_IDENTITY_TAG: $TEMP_IMAGE_TAG

# Included from Container-Scanning.gitlab-ci.yml
container_scanning:
  needs: [docker_build]

# Included from Container-Base.gitlab-ci.yml
docker_dive:
  needs: [docker_build]

# Included from Docker-Deploy.gitlab-ci.yml
.deploy_image:
  variables:
    # Override repository for temp image and tag.  Must be done in job since defined in job template.
    CI_IMAGE_FULL_NAME: $TEMP_IMAGE_REPOSITORY
    CI_IMAGE_IDENTITY_TAG: $TEMP_IMAGE_TAG
