# Collection to consolidate Docker build, lint, scan, and deploy.

include:
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.4.4/collections/Container-Base.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.4.4/jobs/Docker-Build.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.4.4/jobs/Docker-Deploy.gitlab-ci.yml

# Included from Docker-Build.gitlab-ci.yml
docker_build:
  variables:
    # Override repository for temp image and tag.  Must be done in job since defined in job template.
    CI_APPLICATION_REPOSITORY: $TEMP_IMAGE_REPOSITORY
    CI_APPLICATION_TAG: $TEMP_IMAGE_TAG

# Included from Container-Scanning.gitlab-ci.yml
container_scanning:
  needs: [docker_build]

# Included from Container-Base.gitlab-ci.yml
docker_dive:
  needs: [docker_build]

# Included from Docker-Deploy.gitlab-ci.yml
.deploy_image:
  variables:
    # Override repository for temp image and tag.  Must be done in job since defined in job template.
    CI_APPLICATION_REPOSITORY: $TEMP_IMAGE_REPOSITORY
    CI_APPLICATION_TAG: $TEMP_IMAGE_TAG
