# Collection to run GitLab dependency scanning, license management,
# SAST, and secret detection jobs.

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Secret-Detection.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.38/jobs/Json-Schema-Secure.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.38/jobs/OSV-Scanner.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.38/jobs/OWASP-Dependency-Check.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.38/jobs/SAST-Powershell.gitlab-ci.yml

# The overrides below are all included to save artifacts and run on tag pipelines until GitLab
# issue https://gitlab.com/gitlab-org/gitlab/-/issues/225797 is fixed.  Only overrides required
# for Node.js projects for the included templates are specified.

# Included from Dependency-Scanning.gitlab-ci.yml
dependency_scanning:
  artifacts:
    paths:
      - gl-dependency-scanning-report.json

# Included from Dependency-Scanning.gitlab-ci.yml
# Save dependency and SBOM reports if applicable
.cyclone-dx-reports:
  artifacts:
    paths:
      - gl-dependency-scanning-report.json
      - '**/gl-sbom-*.cdx.json'

# Included from Dependency-Scanning.gitlab-ci.yml
.gemnasium-shared-rule:
  exists:
    - '**/Gemfile.lock'
    - '**/composer.lock'
    - '**/gems.locked'
    - '**/go.sum'
    - '**/npm-shrinkwrap.json'
    - '**/package-lock.json'
    - '**/yarn.lock'
    - '**/pnpm-lock.yaml'
    - '**/packages.lock.json'
    - '**/conan.lock'

# Included from Dependency-Scanning.gitlab-ci.yml
gemnasium-dependency_scanning:
  rules:
    - if: $DEPENDENCY_SCANNING_DISABLED == 'true' || $DEPENDENCY_SCANNING_DISABLED == '1'
      when: never
    - if: $DS_EXCLUDED_ANALYZERS =~ /gemnasium([^-]|$)/
      when: never
    - if: |
        ($CI_COMMIT_BRANCH || $CI_COMMIT_TAG || $CI_MERGE_REQUEST_IID) &&
        $GITLAB_FEATURES =~ /\bdependency_scanning\b/ &&
        $CI_GITLAB_FIPS_MODE == 'true'
      exists: !reference [.gemnasium-shared-rule, exists]
      variables:
        DS_IMAGE_SUFFIX: -fips
        DS_REMEDIATE: 'false'
    - if: |
        ($CI_COMMIT_BRANCH || $CI_COMMIT_TAG || $CI_MERGE_REQUEST_IID) &&
        $GITLAB_FEATURES =~ /\bdependency_scanning\b/
      exists: !reference [.gemnasium-shared-rule, exists]

# Included from SAST.gitlab-ci.yml
sast:
  artifacts:
    paths:
      - gl-sast-report.json

# Included from SAST.gitlab-ci.yml
nodejs-scan-sast:
  rules:
    - if: $SAST_DISABLED == 'true' || $SAST_DISABLED == '1'
      when: never
    - if: $SAST_EXCLUDED_ANALYZERS =~ /nodejs-scan/
      when: never
    - if: $CI_COMMIT_BRANCH || $CI_COMMIT_TAG || $CI_MERGE_REQUEST_IID
      exists:
        - '**/package.json'

# Included from SAST.gitlab-ci.yml
semgrep-sast:
  variables:
    SAST_ANALYZER_IMAGE: registry.gitlab.com/gitlab-ci-utils/gitlab-semgrep-plus:1.0.0
  rules:
    - if: $SAST_DISABLED == 'true' || $SAST_DISABLED == '1'
      when: never
    - if: $SAST_EXCLUDED_ANALYZERS =~ /semgrep/
      when: never
    - if: $CI_COMMIT_BRANCH || $CI_COMMIT_TAG || $CI_MERGE_REQUEST_IID
      exists:
        - '**/*.py'
        - '**/*.js'
        - '**/*.jsx'
        - '**/*.ts'
        - '**/*.tsx'
        - '**/*.c'
        - '**/*.go'
        - '**/*.java'
        - '**/*.cs'
        - '**/*.html'
        - '**/*.scala'
        - '**/*.sc'

# Included from Secret-Detection.gitlab-ci.yml
.secret-analyzer:
  artifacts:
    paths:
      - gl-secret-detection-report.json

# Included from Secret-Detection.gitlab-ci.yml
# Resolve MR issues (#165) and simplify override logic by always running a full scan
secret_detection:
  needs: []
  rules:
    - if: $SECRET_DETECTION_DISABLED == 'true' || $SECRET_DETECTION_DISABLED == '1'
      when: never
    - if: $CI_COMMIT_BRANCH || $CI_COMMIT_TAG || $CI_MERGE_REQUEST_IID

# Included from GitLab-Security-Scans.gitlab-ci.yml
# Only run on schedule pipelines
owasp_dependency_check:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'schedule'
