# Collection to consolidate Node build, lint-js/md, and node test.
# Includes alternate rules for schedules that do not allow failure for
# npm check or npm audit, which will trigger notification for job failure.

include:
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.48/collections/Node-Build-Test.gitlab-ci.yml

# Included from Node-Build-Test.gitlab-ci.yml
npm_check:
  extends:
    - .node
    - .schedule_fail_without_renovate

# Included from Node-Build-Test.gitlab-ci.yml
npm_audit:
  rules:
    # OWASP Dependency Check includes NPM audit, so if
    # it is included then disable this job
    - if: $OWASP_DEPENDENCY_CHECK
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: on_success
      allow_failure: false
    - when: on_success
      allow_failure: true
