include:
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.52/collections/All-Projects.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.52/collections/Node-Build-Test-Schedules-Fail.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.52/collections/Node-Version-Tests.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.52/collections/GitLab-Security-Scans-Schedules-Fail.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.52/collections/Npm-Publish-Release.gitlab-ci.yml

# Included from Node-Build-Test-Schedules-Fail.gitlab-ci.yml
npm_check:
  extends:
    - .node
    - .schedule_fail_without_renovate

# Included from GitLab-Security-Scans.gitlab-ci.yml
gemnasium-dependency_scanning:
  # Exclude all dependencies, not used
  needs: []

# Included from GitLab-Security-Scans.gitlab-ci.yml
dependency_scanning:
  # Add build dependency so node_modules is scanned.
  needs:
    - npm_install

# Included from GitLab-Security-Scans.gitlab-ci.yml
sast:
  # Exclude all dependencies otherwise issues found in node_modules will be flagged.
  needs: []

# Included from GitLab-Security-Scans.gitlab-ci.yml
secret_detection:
  # Exclude all dependencies otherwise issues found in node_modules will be flagged.
  needs: []

# Included from GitLab-Security-Scans.gitlab-ci.yml
owasp_dependency_check:
  #  Add build dependency so node_modules is scanned.
  needs:
    - npm_install

# Move to pre-deploy so failure will block npm publish.
# Included from Npm-Publish-Release.gitlab-ci.yml
prepare_release:
  stage: pre-deploy

# Update to specify required jobs.
# Included from Npm-Publish-Release.gitlab-ci.yml
create_release:
  needs:
    - prepare_release
    - npm_publish
