include:
  - project: msclock/gitlab-ci-utils-templates
    ref: v1.0.0
    file:
      - /collections/All-Projects-General.gitlab-ci.yml
  - local: /templates/common.yml

.workflow:
  extends:
    - .rules
  workflow:
    rules:
      - !reference [.workflow, Merge Request]
      - !reference [.workflow, Avoid MR Duplication Pipeline]
      - when: always

workflow: !reference [.workflow, workflow]

# @Description lint codebase with pre-commit
pre-commit:
  stage: lint
  extends:
    - .pre_commit
    - .proxy_backend
  variables:
    CLASH_PROXY_SUB: $PROXY_SUB

# @Description count codes
code_count:
  before_script:
    - |
      sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories

# @Description deploy with mkdocs
pages:
  stage: deploy
  extends:
    - .pages_mkdocs
  variables:
    MKDOCS_EXTRA_PLUGINS: mkdocs-material mkdocs-git-revision-date-localized-plugin
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - |
      pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
      pip config set global.trusted-host mirrors.tuna.tsinghua.edu.cn

# @Description release with semantic_release
semantic_release:
  stage: release
  extends:
    - .release
  variables:
    NPM_SOURCE: https://registry.npm.taobao.org
    RELEASE_EXTRA_PLUGINS: '@semantic-release/changelog @semantic-release/git'
