include:
  - project: msclock/gitlab-ci-utils-templates
    ref: master
    file:
      - /collections/All-Projects-General.gitlab-ci.yml
  - local: /templates/common.yml

.workflow:
  extends:
    - .rules
  workflow:
    rules:
      - !reference [.workflow, Merge Request]
      - !reference [.workflow, Avoid MR Duplication Pipeline]
      - when: always

workflow: !reference [.workflow, workflow]

# @Description lint codebase with pre-commit
pre-commit:
  stage: lint
  extends:
    - .pre_commit
    - .proxy_backend
  variables:
    CLASH_PROXY_SUB: $PROXY_SUB

# @Description deploy with mkdocs
pages:
  stage: deploy
  extends:
    - .proxy_backend
    - .pages-mkdocs
  variables:
    CLASH_PROXY_SUB: $PROXY_SUB
    MKDOCS_EXTRA_PLUGINS: mkdocs-material mkdocs-git-revision-date-localized-plugin
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# @Description release with semantic-release
semantic-release:
  stage: release
  extends:
    - .release
  variables:
    NPM_SOURCE: https://registry.npm.taobao.org
    RELEASE_EXTRA_PLUGINS: '@semantic-release/changelog @semantic-release/git'
