include:
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.6.9/collections/All-Projects.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.6.9/jobs/Pages-Mkdocs.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.6.9/templates/Proxy.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.6.9/.gitlab/includes/Detect-Changes-Build-Images.gitlab-ci.yml

default:
  artifacts:
    expire_in: 1 week

variables:
  LINT_YAML_ENABLE: ''
  LINT_MD_ENABLE: ''
  # Post to run tag pipeline to trigger released pipeline
  RELEASE_POST_PIPELINE_TYPE: tag

.proxy_backend::template:
  script:
    - !reference [.proxy_backend::scripts, Security Check Sensible]
    - !reference [.proxy_backend::scripts, Configure Proxy]
    - git config --global url.https://mirror.ghproxy.com/https://github.com.insteadOf https://github.com

# @Description lint codebase with pre-commit
pre_commit:
  stage: lint
  extends:
    - .proxy_backend
  variables:
    CLASH_PROXY_SUB: $PROXY_SUB

# @Description count codes
code_count:
  before_script:
    - |
      sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories

# @Description test unicode_bidi
unicode_bidi_test:
  before_script:
    - |
      npm config set registry https://registry.npmmirror.com
      npm get registry

._pages_common: &pages_common
  variables:
    VERSION_DOCS: '1'
    MKDOCS_EXTRA_PLUGINS: mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-same-dir
  before_script:
    - |
      pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
      pip config set global.trusted-host mirrors.tuna.tsinghua.edu.cn

# @Description review deploy pages with mkdocs
pages:review:
  <<: *pages_common

# @Description deploy with mkdocs
pages:
  <<: *pages_common

# @Description semantic_release
semantic_release:
  variables:
    NPM_SOURCE: https://registry.npmmirror.com
    RELEASE_EXTRA_PLUGINS: >-
      @semantic-release/changelog
      @semantic-release/git
      semantic-release-replace-plugin
      conventional-changelog-conventionalcommits
      @semantic-release/exec
