include:
  - local: /templates/Proxy.gitlab-ci.yml
  - local: /jobs/Pages-Mkdocs.gitlab-ci.yml
  - local: /collections/All-Projects-General.gitlab-ci.yml
  - local: /collections/Code-Quality.gitlab-ci.yml

variables:
  LINT_YAML_ENABLE: ''
  LINT_MD_ENABLE: ''

# @Description lint codebase with pre-commit
pre_commit:
  stage: lint
  extends:
    - .proxy_backend
  variables:
    CLASH_PROXY_SUB: $PROXY_SUB

# @Description count codes
code_count:
  before_script:
    - |
      sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories

# @Description deploy with mkdocs
pages:
  variables:
    MKDOCS_EXTRA_PLUGINS: mkdocs-material mkdocs-git-revision-date-localized-plugin
  before_script:
    - |
      pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
      pip config set global.trusted-host mirrors.tuna.tsinghua.edu.cn

# @Description semantic_release
semantic_release:
  variables:
    NPM_SOURCE: https://registry.npm.taobao.org
