include:
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.11/jobs/Pages-Mkdocs.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.11/collections/All-Projects-General.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.11/collections/Code-Quality.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.11/.gitlab/includes/Detect-Changes-Build-Images.gitlab-ci.yml

variables:
  LINT_YAML_ENABLE: ''
  LINT_MD_ENABLE: ''

# @Description lint codebase with pre-commit
pre_commit:
  stage: lint
  before_script:
    - |
      git config --global url.https://ghproxy.com/https://github.com.insteadOf https://github.com

# @Description count codes
code_count:
  before_script:
    - |
      sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories

# @Description deploy with mkdocs
pages:
  variables:
    MKDOCS_EXTRA_PLUGINS: mkdocs-material mkdocs-git-revision-date-localized-plugin
  before_script:
    - |
      pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
      pip config set global.trusted-host mirrors.tuna.tsinghua.edu.cn

# @Description semantic_release
semantic_release:
  variables:
    NPM_SOURCE: https://registry.npm.taobao.org
    RELEASE_EXTRA_PLUGINS: '@semantic-release/changelog @semantic-release/git @google/semantic-release-replace-plugin conventional-changelog-conventionalcommits'
