include:
  - project: msclock/gitlab-ci-utils-templates
    ref: master
    file:
      - /collections/All-Projects-General.gitlab-ci.yml
  - local: /templates/common.yml

# @Description lint codebase with pre-commit
pre-commit:
  stage: lint
  extends:
    - .pre_commit
    - .proxy_backend
  variables:
    PRE_COMMIT_DEDUPLICATE_MR_AND_BRANCH: 'false'
    PRE_COMMIT_AUTO_FIX_BRANCH_ONLY: 'true'
    CLASH_PROXY_SUB: $PROXY_SUB
  cache:
    key: pre-commit-cache
    paths:
      - $PRE_COMMIT_HOME

# @Description count codebase
code_count:
  extends:
    - .proxy_backend
  variables:
    CLASH_PROXY_SUB: $PROXY_SUB

# @Description release with semantic-release
semantic-release:
  stage: release
  extends:
    - .release
  variables:
    NPM_SOURCE: https://registry.npm.taobao.org
    RELEASE_EXTRA_PLUGINS: '@semantic-release/changelog @semantic-release/git'
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /^(chore\(release\))/
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always

# @Description deploy with mkdocs
pages:
  stage: deploy
  extends:
    - .proxy_backend
    - .pages-mkdocs
  variables:
    CLASH_PROXY_SUB: $PROXY_SUB
    MKDOCS_EXTRA_PLUGINS: mkdocs-material mkdocs-git-revision-date-localized-plugin
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
