# Job to lint a .pageanrc.json file.

lint_pageanrc:
  image: registry.gitlab.com/gitlab-ci-utils/pagean:9.0.0@sha256:78e05f412c3253aad792dbd9ca06c095c71c9ca71b5c4becdf977a143e7c6838
  stage: lint
  variables:
    PAGEANRC_FILE: .pageanrc.json
  needs: []
  script:
    - pageanrc-lint $PAGEANRC_FILE
