# Job for testing node applications under Windows with Jest.
# By default, uses gitlab.com shared Windows runners. To use
# group Win11 runner, set USE_WINDOWS_11_RUNNER = 'true'.

variables:
  USE_WINDOWS_11_RUNNER: 'false'

node_lts_test_win:
  tags:
    - shared-windows
    - windows
    - windows-1809
  stage: test
  needs: []
  retry:
    max: 2
    when: script_failure
  rules:
    - if: $USE_WINDOWS_11_RUNNER == 'false'
  script:
    - choco install nodejs-lts -y
    - node -v; npm -v
    - npm ci
    - npm test -- --collectCoverage false

node_lts_test_win_11:
  tags:
    - gitlab-ci-utils-windows
  stage: test
  needs: []
  rules:
    - if: $USE_WINDOWS_11_RUNNER == 'true'
  script:
    - node -v; npm -v
    - npm ci
    - npm test -- --collectCoverage false
