# Job using npm-check to check for out of date or unused modules.
# If a Renovate config file is found, only run on schedule and do not allow
# failure. If no Renovate config file is found, also run on other pipelines
# and allow failure.

npm_check:
  extends:
    - .node
    - .schedule_pass_without_renovate
  stage: test
  script:
    - npm install -g npm-check@6.0.1
    - npm-check --skip-unused
