# Job using depcheck to check for unused modules.
# Any dependencies that depcheck erroneously lists as unused can be
# ignored by providing a comma delimited list via the IGNORES variable.

depcheck:
  extends:
    - .node
  stage: test
  allow_failure: true
  script:
    - npm install -g depcheck@1.4.5
    # Specifically list all ignored modules or folders if any identified
    - if [ -f .depcheckrc* ]; then cat .depcheckrc*; fi
    - depcheck
