# Job to check release (tag) history and provide notification after a number of days.
# Assumes $CI_DEFAULT_BRANCH is the published branch.

release_check:
  image: registry.gitlab.com/gitlab-ci-utils/curl-jq:latest
  stage: .post
  variables:
    THRESHOLD: 60
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: always
  needs: []
  script:
    # Get date of latest tagged commit upstream of the current commit
    - TAG_DATE=$(git log --tags --no-walk --max-count=1 --pretty="format:%cI")
    - if [ -z "$TAG_DATE" ]; then echo "No tags found" && exit 0; fi
    # If a date was found, calculate the number of days since and fail if over threshold
    - DAYS=$(( ($(date -d 'now' +%s) - $(date -d "$TAG_DATE" +%s)) / 86400 ))
    - echo "Last release $DAYS days ago"
    - if [ $DAYS -gt $THRESHOLD ]; then exit 1; fi
