# Collection to consolidate Node build, lint-js/md, and node test.

include:
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.6.4/templates/Node-Test.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.6.4/collections/Code-Quality-Npm.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.6.4/jobs/Depcheck.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.6.4/jobs/Lint-Npm-Lockfile.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.6.4/jobs/Lint-Npm-Package.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.6.4/jobs/Node-LTS-Test.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.6.4/jobs/Node-Sbom.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.6.4/jobs/Npm-Audit.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.6.4/jobs/Npm-Check.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.6.4/jobs/Npm-Install.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.6.4/jobs/Socket.gitlab-ci.yml

# Included from Npm-Lint-Js.gitlab-ci.yml
lint_js:
  needs:
    - npm_install

# Included from Npm-Lint-Md.gitlab-ci.yml
lint_md:
  needs:
    - npm_install

# Included from Npm-Lint-Prettier.gitlab-ci.yml
lint_prettier:
  needs:
    - npm_install

# Included from Npm-Check.gitlab-ci.yml
npm_check:
  needs:
    - npm_install

# Included from Depcheck.gitlab-ci.yml
depcheck:
  needs:
    - npm_install

# Included from Npm-Audit.gitlab-ci.yml
npm_audit:
  needs:
    - npm_install

# Included from Node-Sbom.gitlab-ci.yml
node_sbom:
  needs:
    - npm_install
