# Job to build and push a docker image with repository/tag to match the container scanning job.

docker_build:
  extends:
    - .container::dind
    - .container::image_common_settings
  stage: container-build
  script:
    - !reference [.container::dind, script]
    - !reference [.container::image_common_settings, script]
    - docker build --pull -f ${DOCKERFILE} ${IMAGE_LABELS} -t ${CI_IMAGE_FULL_NAME}:${CI_IMAGE_IDENTITY_TAG} .
    - docker push ${CI_IMAGE_FULL_NAME}:${CI_IMAGE_IDENTITY_TAG}
