# Template and jobs to pull a docker image with repository/tag matching the Docker build job and tag as follows:
#   - Commit Tags: tag image with commit tag
#   - $CI_DEFAULT_BRANCH branch: tag image with "latest"
#   - Other branches or MR: tag image with branch name

.deploy_image:
  extends: .dind
  variables:
    # These are the variables and default values for repository/tag in the container scanning job.
    # They are used here so they can be overridden once globally (if desired).
    CI_APPLICATION_REPOSITORY: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
    CI_APPLICATION_TAG: $CI_COMMIT_SHA
    GIT_STRATEGY: none
  stage: container-deploy
  dependencies: []
  script:
    - !reference [.dind, script]
    - |
      export SOURCE_IMAGE=${CI_APPLICATION_REPOSITORY}:${CI_APPLICATION_TAG}
      echo SOURCE_IMAGE: $SOURCE_IMAGE
      export TARGET_IMAGE=$CI_REGISTRY_IMAGE:$IMAGE_TAG
      echo TARGET_IMAGE: $TARGET_IMAGE
    - docker pull $SOURCE_IMAGE
    - docker tag $SOURCE_IMAGE $TARGET_IMAGE
    - docker push $TARGET_IMAGE

deploy_branch:
  extends: .deploy_image
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_TAG
      variables:
        IMAGE_TAG: latest
    - if: ($CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH) || $CI_MERGE_REQUEST_IID
      variables:
        IMAGE_TAG: $CI_COMMIT_REF_SLUG

deploy_tag:
  extends: .deploy_image
  variables:
    IMAGE_TAG: $CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG
