# Job to lint package-lock.json to ensure all packages come from
# npm, over https, with an integrity value

lint_lockfile:
  extends:
    - .node
  stage: lint
  rules:
    - exists:
        - '**/package-lock.json'
  needs: []
  script:
    - npm install -g lockfile-lint@4.12.1
    - lockfile-lint --path package-lock.json --allowed-hosts npm --validate-https --validate-integrity --validate-package-names
