# Job to lint all Linux shell scripts in the project.

lint_sh:
  image: ubuntu:lunar
  stage: lint
  needs: []
  allow_failure: true
  rules:
    - exists:
        - '**/*.sh'
  script:
    - >
      apt update &&
      apt -y install --no-install-recommends shellcheck &&
      shellcheck --version
    - find . -type f -name "*.sh" -exec shellcheck {} +
