# Job to lint all markdown in the project. Uses default markdownlint
# configuration file if no project-specific configuration is found.

lint_md:
  extends:
    - .node
  stage: lint
  variables:
    CONFIG_FILE_LINK: https://gitlab.com/gitlab-ci-utils/config-files/-/raw/9.2.0/Linters/.markdownlint.json
  needs: []
  rules:
    - if: $LINT_MD_ENABLE
      exists:
        - '**/*.md'
  script:
    - npm install -g markdownlint-cli2@0.9.2
    # If setting files do not exist, get default from config-file project
    - |
      if [ ! -f .markdownlint.json ] && \
        [ ! -f .markdownlint.jsonc ] && \
        [ ! -f .markdownlint.yaml ] && \
        [ ! -f .markdownlint.yml ]; then
        wget $CONFIG_FILE_LINK
      fi
    - markdownlint-cli2 "**/*.md" "#node_modules"

variables:
  LINT_MD_ENABLE: '1'
