# Job to lint all YAML in the project. Uses default yamllint
# configuration file if no project-specific configuration is found.

include:
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.3.1/templates/Python.gitlab-ci.yml

lint_yaml:
  extends:
    - .python
  stage: lint
  variables:
    CONFIG_FILE_LINK: https://gitlab.com/gitlab-ci-utils/config-files/-/raw/9.0.1/Linters/.yamllint.yml
  needs: []
  script:
    - pip install yamllint==1.32.0
    # If none of the three default config file names exist, get default
    # file from the config-files project.
    - >
      if [ ! -f .yamllint ] && [ ! -f .yamllint.yml ] && [ ! -f .yamllint.yaml ];
      then (wget $CONFIG_FILE_LINK) fi
    - yamllint .
