# Job to lint all powershell files in the project
# using https://github.com/PowerShell/PSScriptAnalyzer

lint_powershell:
  image: mcr.microsoft.com/powershell:7.4-alpine-3.17@sha256:8e0a5faa975b276b3037c2f262af9f1f75d178ac41b8e5329306775e5a937272
  stage: lint
  needs: []
  rules:
    - exists:
        - '**/*.ps1'
        - '**/*.psm1'
  script:
    - pwsh -c "Install-Module PSScriptAnalyzer -Force"
    - pwsh -c "Invoke-ScriptAnalyzer -Path . -EnableExit"
