# Job to lint all powershell files in the project
# using https://github.com/PowerShell/PSScriptAnalyzer

lint_powershell:
  image: mcr.microsoft.com/powershell:7.3-alpine-3.17@sha256:2ddd452fd54303a20ab231a2997670d80488f5b0ac8e4977137d757d143a7d7c
  stage: lint
  needs: []
  rules:
    - exists:
        - '**/*.ps1'
        - '**/*.psm1'
  script:
    - pwsh -c "Install-Module PSScriptAnalyzer -Force"
    - pwsh -c "Invoke-ScriptAnalyzer -Path . -EnableExit"
