# Job for scanning with the OWASP Dependency Check tool.
# Variable ODC_ADDITIONAL_ARGS can be populated to add any
# required additional CLI arg (e.g. project-specific suppression).

# Add variable if this job is included to disable redundant jobs
variables:
  OWASP_DEPENDENCY_CHECK: owasp_dependency_check

owasp_dependency_check:
  image:
    name: registry.gitlab.com/gitlab-ci-utils/docker-dependency-check:latest
    entrypoint: ['']
  stage: test
  script:
    - >
      /usr/share/dependency-check/bin/dependency-check.sh
      --scan "./" --format ALL
      --project "$CI_PROJECT_NAME" --failOnCVSS 0
      --suppression /suppressions/npm_fp_suppression.xml
      --suppression /suppressions/npm_na_suppressions.xml
      $ODC_ADDITIONAL_ARGS
  allow_failure: true
  artifacts:
    when: always
    expose_as: OWASP Dependency Check Report
    paths:
      - dependency-check-report.html
      - dependency-check-report.json
