# Job to run mkdocs deployment

include:
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.27/templates/Pages-Mkdocs.gitlab-ci.yml

# @Description deploy pages with mkdocs, the named pages is a must for trigger pages deploy job
pages:
  stage: deploy
  extends:
    - .pages_mkdocs
  rules:
    - if: |
        $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ||
        $CI_COMMIT_TAG
      exists:
        - mkdocs.yml
