include:
  - local: /templates/Release.gitlab-ci.yml

# @Description release with semantic_release
semantic_release:
  stage: release
  extends:
    - .release

# @Description post to trigger pipeline
post_release:
  stage: .post
  needs:
    - semantic_release
  extends:
    - .post_pipelilne
