include:
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.1.0/templates/Release.gitlab-ci.yml

# @Description release with semantic_release
semantic_release:
  stage: pre-release
  extends:
    - .release

# @Description trigger tag for semantic_release
post_release:
  stage: release
  needs:
    - semantic_release
  extends:
    - .post_pipelilne
