# Job check for injection attacks in powershell files
# using https://github.com/PowerShell/PSScriptAnalyzer
# and https://www.powershellgallery.com/packages/InjectionHunter.
# The name is formatted to match the GitLab SAST jobs.

powershell-sast:
  image: mcr.microsoft.com/powershell:7.3-alpine-3.17@sha256:2ddd452fd54303a20ab231a2997670d80488f5b0ac8e4977137d757d143a7d7c
  stage: test
  needs: []
  allow_failure: true
  rules:
    - exists:
        - '**/*.ps1'
        - '**/*.psm1'
  script:
    - pwsh -c "Install-Module PSScriptAnalyzer, InjectionHunter -Force"
    - pwsh -c "Invoke-ScriptAnalyzer -Path . -CustomRulePath (Get-Module InjectionHunter -List | % Path) -EnableExit"
