# Job check for injection attacks in powershell files
# using https://github.com/PowerShell/PSScriptAnalyzer
# and https://www.powershellgallery.com/packages/InjectionHunter.
# The name is formatted to match the GitLab SAST jobs.

powershell-sast:
  image: mcr.microsoft.com/powershell:7.4-alpine-3.17@sha256:b8fbab46c911d9bb034cae20540a6ad65c4863df77b43bec7c2dd242520403a5
  stage: test
  needs: []
  allow_failure: true
  rules:
    - exists:
        - '**/*.ps1'
        - '**/*.psm1'
  script:
    - pwsh -c "Install-Module PSScriptAnalyzer, InjectionHunter -Force"
    - pwsh -c "Invoke-ScriptAnalyzer -Path . -CustomRulePath (Get-Module InjectionHunter -List | % Path) -EnableExit"
