# Job check for injection attacks in powershell files
# using https://github.com/PowerShell/PSScriptAnalyzer
# and https://www.powershellgallery.com/packages/InjectionHunter.
# The name is formatted to match the GitLab SAST jobs.

powershell-sast:
  image: mcr.microsoft.com/powershell:7.3-alpine-3.17@sha256:6e07aefdc73d2139b65c17266281fc7cd36f1d8ef649069f3f613632da678986
  stage: test
  needs: []
  allow_failure: true
  rules:
    - exists:
        - '**/*.ps1'
        - '**/*.psm1'
  script:
    - pwsh -c "Install-Module PSScriptAnalyzer, InjectionHunter -Force"
    - pwsh -c "Invoke-ScriptAnalyzer -Path . -CustomRulePath (Get-Module InjectionHunter -List | % Path) -EnableExit"
