# @Require gitlab-ci-templates/templates/Rules.gitlab-ci.yml

.general_workflow:
  extends:
    - .rules
  workflow:
    rules:
      - !reference [.general_workflow, Avoid MR Duplication Pipeline But Trigger]
      - when: always

workflow: !reference [.general_workflow, workflow]

default:
  interruptible: true
  artifacts:
    expire_in: 15 days
