.general_workflow:
  extends:
    - .rules
  workflow:
    rules:
      - !reference [.general_workflow, Avoid MR Duplication Pipeline]
      - when: always

workflow: !reference [.general_workflow, workflow]

default:
  artifacts:
    expire_in: 15 days
