include:
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.2.0/templates/Rules.gitlab-ci.yml

.workflow:
  extends:
    - .rules
  workflow:
    rules:
      - !reference [.workflow, Avoid MR Duplication Pipeline]
      - when: always

workflow: !reference [.workflow, workflow]

default:
  artifacts:
    expire_in: 15 days
