# @Description template of the base image of devcontainer
.devcontainer:
  image: msclock/devcontainer:2023-08-10T04-27-58Z

# @Description devcontainer build
.devcontainer::build:
  extends:
    - .devcontainer
  variables:
    # Full image name including registry and tag
    IMAGE_NAME: ''
    # If on, push the image
    PUSH: ''
    # Platform images to build
    PLATFORM: ''
    # Folder where to store devcontainer configuration
    WORKING_DIRECTORY: ''
    # If on, pin the generated image to the latest
    PIN_LATEST: ''
  script:
    - |
      build_extra=(--workspace-folder ${WORKING_DIRECTORY})

      if [ -n "$IMAGE_NAME" ]; then
        build_extra+=(--image-name "$IMAGE_NAME")
        if [ -n "$PIN_LATEST" ]; then
          build_extra+=(--image-name "${IMAGE_NAME%:*}:latest")
        fi
      fi

      if [ -n "$PUSH" ]; then
        build_extra+=(--push)
      fi

      if [ -n "$PLATFORM" ]; then
        build_extra+=(--platform "$PLATFORM")
      fi

      # build image by devcontainer
      devcontainer build "${build_extra[@]}"
