# @Description template of the base image of devcontainer
.devcontainer:
  image: msclock/devcontainer:2023-08-10T04-27-58Z

# @Description devcontainer build
.devcontainer::build:
  extends:
    - .devcontainer
  variables:
    IMAGE_NAME: ''
    PUSH: ''
    PLATFORM: ''
    SUB_FOLDER: ''
  script:
    - |
      set -x

      build_extra=(--workspace-folder .)

      if [ -n "$SUB_FOLDER" ]; then
        build_extra+=(--config "$SUB_FOLDER")
      fi

      if [ -n "$IMAGE_NAME" ]; then
        build_extra+=(--image-name "$IMAGE_NAME")
      fi

      if [ -n "$PUSH" ]; then
        build_extra+=(--push)
      fi

      if [ -n "$PLATFORM" ]; then
        build_extra+=(--platform "$PLATFORM")
      fi

      # build image by devcontainer
      devcontainer build "${build_extra[@]}"
