# Template for linting template files with djlint, which can be extended
# for various languages. Assumes the following variables are specified:
#   CONFIG_FILE_LINK: url for the default config file

.djlint:
  extends:
    - .python
  stage: lint
  needs: []
  script:
    - pip install djlint==1.32.1
    # If settings file does not exist, get default from config-file project
    # and save as .djlintrc
    - if [ ! -f .djlintrc ]; then (wget -O .djlintrc $CONFIG_FILE_LINK) fi
    - djlint --check --lint .
