# Template for all docker-in-docker jobs.

.dind:
  image: docker:24.0.6-alpine3.18
  services:
    - docker:24.0.6-dind-alpine3.18
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker info
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
