# This presents a template for making mkdocs pages deployment.
# See https://www.mkdocs.org/.
#
# To configure the template refers to the variables section.

# @Description template for deploy mkdocs
.pages_mkdocs:
  stage: deploy
  variables:
    # The pip cache
    PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
    # The branch to deploy when enable the VERSION_DOCS.
    PAGES_BRANCH: gl-pages
    # Specifies whether to use mike to deploy mkdocs docs.
    # And Only deploy when enable the VERSION_DOCS and CI_COMMIT_TAG.
    VERSION_DOCS: ''
    # Specifies the extra mkdocs plugins.
    MKDOCS_EXTRA_PLUGINS: ''
  image: python:3.11-bullseye
  dependencies: []
  script:
    - !reference [.security_check_sensible, script]
    - !reference [.security_git_config, script]
    - |
      echo "Install mkdocs plugins: mkdocs ${MKDOCS_EXTRA_PLUGINS}" >> /dev/stderr
      pip install mkdocs==1.5.3 ${MKDOCS_EXTRA_PLUGINS}

      # Only deploy when enable the VERSION_DOCS and CI_COMMIT_TAG
      if [[ -n "$VERSION_DOCS" && -n "$CI_COMMIT_TAG" ]]; then
        pip install mike==2.0.0

        git fetch origin $PAGES_BRANCH || echo "Pages branch not deployed yet." >> /dev/stderr
        git checkout -b $PAGES_BRANCH origin/$PAGES_BRANCH || echo "Pages branch not deployed yet." >> /dev/stderr
        git checkout $CI_COMMIT_SHA

        mike_common_options=(--deploy-prefix public --push --branch $PAGES_BRANCH)
        mike deploy "${mike_common_options[@]}" --update-aliases ${CI_COMMIT_TAG} latest
        mike set-default "${mike_common_options[@]}" latest
        git checkout $PAGES_BRANCH -- public/
      else
        mkdocs build --site-dir public/ --no-directory-urls
      fi
  artifacts:
    paths:
      - public/
  cache:
    key: pages-pip-cache
    paths:
      - $PIP_CACHE_DIR
