# This presents a template for making mkdocs pages deployment.
# See https://www.mkdocs.org/.
#
# To configure the template refers to the variables section.

# @Description template for deploy mkdocs
.pages_mkdocs:
  stage: deploy
  variables:
    # The pip cache
    PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
    # The branch to deploy when enable the VRESION_DOCS.
    PAGES_BRANCH: gl-pages
    # Specifies whether to use mike to deploy mkdocs docs.
    VRESION_DOCS: ''
    # Specifies the extra mkdocs plugins.
    MKDOCS_EXTRA_PLUGINS: ''
  image: python:3.11-bullseye
  script:
    - !reference [.security_check_sensible, script]
    - !reference [.security_git_config, script]
    - |
      echo "Install mkdocs plugins: mkdocs ${MKDOCS_EXTRA_PLUGINS}" >> /dev/stderr
      pip install mkdocs ${MKDOCS_EXTRA_PLUGINS}

      if [[ -n "$VRESION_DOCS" ]]; then
        pip install mike

        git fetch origin $PAGES_BRANCH
        git checkout -b $PAGES_BRANCH origin/$PAGES_BRANCH || echo "Pages branch not deployed yet."
        git checkout $CI_COMMIT_SHA

        mike deploy --rebase --prefix public -p -b $PAGES_BRANCH -u $CI_COMMIT_TAG latest
        mike set-default --rebase --prefix public -p -b $PAGES_BRANCH latest
        git checkout $PAGES_BRANCH -- public/
      else
        mkdocs build --site-dir public
      fi
  artifacts:
    paths:
      - public/
  cache:
    key: pages-pip-cache
    paths:
      - $PIP_CACHE_DIR
