# @Description proxy backend based on clash
.proxy_backend:
  services:
    - name: msclock/clash:2023-08-10T04-27-58Z
      alias: proxy_backend
      entrypoint:
        - ''
      command:
        - sh
        - -c
        - set -xe && wget $CLASH_PROXY_SUB -O /root/.config/clash/config.yaml && ./clash
  variables:
    CLASH_PROXY_SUB: ''
    PROXY_WHITE_LIST: 10.0.0.0/8,192.168.0.0/16,127.0.0.1,172.16.0.0/16,$CI_SERVER_HOST
    ENABLE_PROXY: '1'
  before_script:
    - !reference [.security_check_sensible, script]
    - |
      if [[ -n "$ENABLE_PROXY" ]]; then
        if [[ -z "$CLASH_PROXY_SUB" ]]; then
          echo "No proxy subscribe found." >> /dev/stderr
          exit 1
        fi

        export HTTP_PROXY="http://proxy_backend:7890"
        export http_proxy="$HTTP_PROXY"

        export HTTPS_PROXY="$HTTP_PROXY"
        export https_proxy="$HTTP_PROXY"

        export FTP_PROXY=$HTTP_PROXY
        export ftp_proxy=$HTTP_PROXY

        export ALL_PROXY=$HTTP_PROXY
        export all_proxy=$HTTP_PROXY

        export NO_PROXY="$PROXY_WHITE_LIST"
        export no_proxy="$NO_PROXY"
        sleep 3 # wait for proxy_backend is ready
      fi
