# Template for all Python jobs using the latest Alpine image.
# Includes variables with standard pip setting to avoid repeating
# in all jobs. For boolean variables, set to 0 to disable.
# See https://pip.pypa.io/en/stable/topics/configuration/.

.python:
  image: python:3.11.5-alpine3.18@sha256:e5d592c422d6e527cb946ae6abb1886c511a5e163d3543865f5a5b9b61c01584
  variables:
    PIP_ROOT_USER_ACTION: ignore
    PIP_NO_CACHE_DIR: 1
    PIP_DISABLE_PIP_VERSION_CHECK: 1
