# Template for all Python jobs using the latest Alpine image.
# Includes variables with standard pip setting to avoid repeating
# in all jobs. For boolean variables, set to 0 to disable.
# See https://pip.pypa.io/en/stable/topics/configuration/.

.python:
  image: python:3.11.5-alpine3.18@sha256:5d769f990397afbb2aca24b0655e404c0f2806d268f454b052e81e39d87abf42
  variables:
    PIP_ROOT_USER_ACTION: ignore
    PIP_NO_CACHE_DIR: 1
    PIP_DISABLE_PIP_VERSION_CHECK: 1
