# This presents semantic release templates for automatic release management
# based on semantic-release, see https://www.npmjs.com/package/semantic-release.
#
# To configure the template refers to the variables section.
#
# Normally, the templates can apply the release workflows:
#   - [Distribution channels](https://semantic-release.gitbook.io/semantic-release/recipes/release-workflow/distribution-channels)
#   - [Maintenance release](https://semantic-release.gitbook.io/semantic-release/recipes/release-workflow/maintenance-releases)
#   - [Pre-release](https://semantic-release.gitbook.io/semantic-release/recipes/release-workflow/pre-releases)
#
# For more information about semantic-release, see https://github.com/semantic-release/semantic-release.

variables:
  # Optional. Post to run a pipeline to trigger released pipeline,
  # and the value can be '', 'tag' or 'branch'
  RELEASE_POST_PIPELINE_TYPE: ''

.release::scripts:
  Security Check Sensible: !reference [.security_check_sensible, script]
  Setup Git: !reference [.common_git::template, script]
  Set Npm Source: |-
    echo "Configuring NPM_SOURCE: $NPM_SOURCE when it is set"
    if [[ -n "$NPM_SOURCE" ]]; then
      npm config set registry "$NPM_SOURCE"
      npm get registry
    fi
  Setup Semantic Release: |-
    echo "Install semantic release plugins..." >> /dev/stderr
    npm install -g semantic-release \
      @semantic-release/release-notes-generator \
      @semantic-release/gitlab $RELEASE_EXTRA_PLUGINS
  Generate Preset Releaserc If Needed: |-
    echo "Generate preset releaserc when USING_PRESET_RELEASERC: $_PRESET_RELEASERC_FILE is set"
    if [[ -n "$USING_PRESET_RELEASERC" ]]; then
      echo "Generating preset releaserc $_PRESET_RELEASERC_FILE..."
      echo "$_PRESET_RELEASERC_CONFIG" > "$_PRESET_RELEASERC_FILE"
    fi
  Update Local Tags: |-
    echo "Update the local tags" >> /dev/stderr
    git fetch --tags --force
  Info Tags Now: |-
    echo "Info local and remote tags now" >> /dev/stderr
    if [[ $CI_DEBUG_TRACE =~ ^(1|true)$ ]]; then
      echo "Local tags:" >> /dev/stderr
      git tag -l
      echo "Remote tags:" >> /dev/stderr
      git ls-remote --tags origin
    fi
  Delete Not Existing Local Tags: |-
    echo "Delete the local tags that no longer exist on the remote repository" >> /dev/stderr
    git fetch origin --prune --prune-tags
  Remove Conflicting Release And Tags: |-
    echo "Remove conflicting release and delete the existing tag and release if possible"
    if [[ -n "$OVERRIDE_RELEASE" ]]; then
      _dry_run_output=$(semantic-release -d --ci)
      _verify_version=$(echo "$_dry_run_output" | grep -oP "(?<=Skip ).+(?= tag creation in dry-run mode)") || true
      if [[ $(git tag -l) =~ (^|[[:space:]])"$_verify_version"($|[[:space:]]) ]]; then
        echo "Found and delete conflicting tag $_verify_version"
        git push origin :refs/tags/"$_verify_version" || true
        git tag -d "$_verify_version"

        echo "Delete release if possible"
        curl --header "PRIVATE-TOKEN: ${GITLAB_TOKEN:-$CI_JOB_TOKEN}" \
          --request DELETE "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases/$_verify_version" || true
      else
        echo "No conflicting release found"
      fi
    fi
  Run Semantic Release: |-
    echo "Run semantic release" >> /dev/stderr
    if [[ -z "$SEMANTIC_RELEASE_OPTIONS" ]]; then
      _release_output=$(semantic-release)
    else
      echo "Be careful!! CLI arguments take precedence over options configured in the configuration file"
      _release_output=$(semantic-release "$SEMANTIC_RELEASE_OPTIONS")
    fi
    echo -e "Semantic Release Output:\n$_release_output"
  Expose Release Version: |-
    echo "Expose the release version to semantic.env" >> /dev/stderr
    new_release_version=$(echo "$_release_output" | grep -oP "(?<=Published release ).+(?= on)") || true
    echo "new_release_version=$new_release_version" >> semantic.env
  Clean Up Preset Releaserc: |-
    echo "Clean up preset releaserc when USING_PRESET_RELEASERC: $_PRESET_RELEASERC_FILE is set"
    if [[ -n "$USING_PRESET_RELEASERC" && -f "$_PRESET_RELEASERC_FILE" ]]; then
      rm -f "$_PRESET_RELEASERC_FILE"
    fi

.release::template:
  script:
    - !reference [.release::scripts, Security Check Sensible]
    - !reference [.release::scripts, Setup Git]
    - !reference [.release::scripts, Set Npm Source]
    - !reference [.release::scripts, Setup Semantic Release]
    - !reference [.release::scripts, Generate Preset Releaserc If Needed]
    - !reference [.release::scripts, Update Local Tags]
    - !reference [.release::scripts, Info Tags Now]
    - !reference [.release::scripts, Delete Not Existing Local Tags]
    - !reference [.release::scripts, Remove Conflicting Release And Tags]
    - !reference [.release::scripts, Run Semantic Release]
    - !reference [.release::scripts, Expose Release Version]

# @Description template for release publish
.release:
  image: msclock/semantic-release:2023-11-24T06-11-45Z
  rules:
    - !reference [.rules, Skip Release Commits]
    - if: |
        $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ||
        $CI_COMMIT_REF_NAME =~ /^(alpha|beta|next|next-major)$/ ||
        $CI_COMMIT_REF_NAME =~ /^+([0-9])?(.{+([0-9]),x}).x$/
  variables:
    # Optional. Extra plugins for semantic-release to install. Default to the below plugins are for making a release
    # with preset release config _PRESEST_RELEASERC_CONFIG.
    RELEASE_EXTRA_PLUGINS: >-
      @semantic-release/changelog
      @semantic-release/git
      @semantic-release/exec
      conventional-changelog-conventionalcommits
    # Optional. If on, the older release will be overwritten by the new release.
    OVERRIDE_RELEASE: ''
    # Optional. If on, the triggered release will apply the preset release config _PRESEST_RELEASERC_CONFIG.
    USING_PRESET_RELEASERC: ''
    # Optional. The preset release config _PRESEST_RELEASERC_CONFIG saved in _PRESET_RELEASERC_FILE
    _PRESET_RELEASERC_FILE: .releaserc.js
    # Optional. The default preset release config for semantic-release, more details
    # see https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md
    _PRESET_RELEASERC_CONFIG: |
      module.exports = {
        branches: [
          "+([0-9])?(.{+([0-9]),x}).x",
          "$CI_DEFAULT_BRANCH",
          "next",
          "next-major",
          { name: "beta", prerelease: true },
          { name: "alpha", prerelease: true },
        ],
        plugins: [
          [
            "@semantic-release/commit-analyzer",
            {
              preset: "angular",
              releaseRules: [
                { breaking: true, release: "major" },
                { type: "feat", release: "minor" },
                { type: "fix", release: "patch" },
                { type: "style", release: "patch" },
                { type: "refactor", release: "patch" },
                { type: "perf", release: "patch" },
                { type: "revert", release: "patch" },
                { type: "chore", scope: "deps", release: "patch" },
                { type: "build", release: false },
                { type: "ci", release: false },
                { type: "docs", release: false },
                { type: "test", release: false },
              ],
              parserOpts: {
                noteKeywords: ["BREAKING CHANGE", "BREAKING CHANGES", "BREAKING"]
              },
            },
          ],
          [
            "@semantic-release/release-notes-generator",
            {
              preset: "conventionalcommits",
              presetConfig: {
                types: [
                  { type: "feat", section: "Features" },
                  { type: "fix", section: "Bug Fixes" },
                  { type: "style", section: "Style" },
                  { type: "refactor", section: "Refactor" },
                  { type: "perf", section: "Performance" },
                  { type: "revert", section: "Reverts" },
                  { type: "chore", scope: "deps", section: "Dependencies" },
                  { type: "chore", section: "Chores" },
                  { type: "build", section: "Build" },
                  { type: "ci", section: "CI" },
                  { type: "docs", section: "Docs" },
                  { type: "test", section: "Tests" },
                ],
              },
              parserOpts: {
                noteKeywords: ["BREAKING CHANGE", "BREAKING CHANGES", "BREAKING"]
              },
            },
          ],
          ["@semantic-release/changelog", { changelogFile: "CHANGELOG.md", }],
          [
            "@semantic-release/exec",
            {
              publishCmd: [
                "git tag -a -f v$${nextRelease.version} --cleanup=whitespace -m \"$${nextRelease.notes}\"",
                "git push --force origin v$${nextRelease.version}"
              ].join(" && "),
            }
          ],
          [
            "@semantic-release/git",
            {
              assets: ["CHANGELOG.md"],
              message: "chore(release): $${nextRelease.version} [skip ci]\n\n$${nextRelease.notes}",
            },
          ],
          "@semantic-release/gitlab",
        ],
      };
    # Optional. NPM registry to speed up dependencies installation.
    NPM_SOURCE: ''
    # Optional. Options for semantic-release cli.
    SEMANTIC_RELEASE_OPTIONS: ''
    # Optional. The api of gitlab for semantic-release
    GITLAB_PREFIX: /api/v4
    # Optional. The instance of gitlab
    GITLAB_URL: $CI_SERVER_URL
  script: !reference [.release::template, script]
  after_script:
    # Finally, remove the preset releaserc file
    - !reference [.release::scripts, Clean Up Preset Releaserc]
  artifacts:
    reports:
      dotenv: semantic.env # Expose the new release version to dotenv

.post_pipeline::scripts:
  Skip Non-Release Commits: |-
    echo "Skip post release pipeline because new_release_version is not set" >> /dev/stderr
    if [[ -z "$new_release_version" ]]; then
      exit 0
    fi
  Schedule Pipeline For Tag: |-
    echo "Schedule pipeline for tag $new_release_version" >> /dev/stderr
    if [[ "$RELEASE_POST_PIPELINE_TYPE" == "tag" ]]; then
      export SCHEDULE_REF="v$new_release_version"
    fi
  Schedule Pipeline For Branch: |-
    if [[ "$RELEASE_POST_PIPELINE_TYPE" == "branch" ]]; then
      if [[ -z "$CI_COMMIT_BRANCH" ]]; then
        echo "Invalid schedule pipeline, and CI_COMMIT_BRANCH must be set if RELEASE_POST_PIPELINE_TYPE is branch" >> /dev/stderr
        exit 1
      fi
      export SCHEDULE_REF="$CI_COMMIT_BRANCH"
    fi
  Info Post Schedule Pipeline: |-
    echo "Ready to schedule pipeline type: $RELEASE_POST_PIPELINE_TYPE, ref: $SCHEDULE_REF"

# @Description steps constraints template
.post_pipeline::template:
  script:
    - !reference [.post_pipeline::scripts, Skip Non-Release Commits]
    - !reference [.post_pipeline::scripts, Schedule Pipeline For Tag]
    - !reference [.post_pipeline::scripts, Schedule Pipeline For Branch]
    - !reference [.post_pipeline::scripts, Info Post Schedule Pipeline]

# @Description post release pipeline, default to run tag post pipeline
.post_pipelilne:
  extends:
    - .schedule_pipeline
  rules:
    - !reference [.rules, Skip Release Commits]
    - if: |
        ( $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ||
        $CI_COMMIT_REF_NAME =~ /^(alpha|beta|next|next-major)$/ ||
        $CI_COMMIT_REF_NAME =~ /^+([0-9])?(.{+([0-9]),x}).x$/ ) &&
        $RELEASE_POST_PIPELINE_TYPE
  before_script: !reference [.post_pipeline::template, script]
