# Job using @cyclonedx/cyclonedx-npm to generate a software
# bill-of-materials (SBOM) per https://cyclonedx.org/
#
# SBOM_TYPE must be one of "application", "firmware", "library".
#
# SBOM_CLI_ARGS can be used to insert any other CLI arguments, see
# https://github.com/CycloneDX/cyclonedx-node-npm for details. This
# can be used for multiple arguments, space delimited, for example:
#   SBOM_CLI_ARGS: '--package-lock-only --output-reproducible'

node_sbom:
  extends:
    - .node
  stage: test
  variables:
    SBOM_TYPE: library
  script:
    - npm install -g @cyclonedx/cyclonedx-npm@1.14.0
    - cyclonedx-npm --output-file bom.json --mc-type $SBOM_TYPE --omit dev --short-PURLs $SBOM_CLI_ARGS
  after_script:
    # Add artificial metrics report to collect release evidence
    - echo 'node_sbom run' > metrics.txt
  artifacts:
    paths:
      - bom.json
    reports:
      # Add artificial metrics report to collect release evidence
      metrics: metrics.txt
      cyclonedx: bom.json
