# Job performing npm ci and saves as artifacts for subsequent jobs.
# For details on "npm ci" vs "npm install" see https://docs.npmjs.com/cli/ci.html

npm_install:
  extends:
    - .node
  stage: prepare
  needs: []
  cache:
    key: $CI_PROJECT_NAME-npm
    paths:
      - .npm/
  script:
    - npm ci --cache .npm --prefer-offline
  artifacts:
    expire_in: 30 days
    paths:
      - node_modules/
