# Publish an NPM package via CI
# Assumes variable NPM_TOKEN is defined with the authentication token.
# Also checks that the package.json version matches the current git tag.

tag_version_check:
  image: registry.gitlab.com/gitlab-ci-utils/curl-jq:latest
  stage: pre-deploy
  rules:
    - if: $CI_COMMIT_TAG
  needs: []
  script:
    - PACKAGE_VERSION=$(cat package.json | jq -r '.version')
    - |
      if [ $CI_COMMIT_TAG == $PACKAGE_VERSION ]; then
        exit 0;
      else
        echo "package.json version does not match git tag" && exit 1;
      fi

npm_publish:
  extends:
    - .node
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  dependencies:
    - npm_install
  environment:
    name: production
    deployment_tier: production
  script:
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - npm publish
