name: build pre-commit image

on:
  push:
    paths:
      - "images/pre-commit/**"

jobs:
  pre-commit-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_ID }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}

      - name: Pre-build image and push to DockerHub
        uses: devcontainers/ci@v0.3
        with:
          subFolder: images/pre-commit
          imageName: msclock/pre-commit
          cacheFrom: msclock/pre-commit
          push: always
