name: mirror to gitlab

on:
  push:
    branches:
      - main

jobs:

  gitlab:
    runs-on: ubuntu-latest
    name: mirror to gitlab

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: mirror-to-gitlab
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: https://gitlab.com/msclock/gitlab-ci-templates.git
          GIT_USERNAME: ${{ github.repository_owner }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
