name: mirror to gitlab

on:
  push:

jobs:

  gitlab:
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch
    name: mirror to gitlab

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: mirror-to-gitlab
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: https://gitlab.com/msclock/gitlab-ci-templates.git
          GIT_USERNAME: ${{ github.repository_owner }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          PUSH_ALL_REFS: 'false'
          GIT_PUSH_ARGS: --force --prune
