include:
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.17/templates/Devcontainer.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.17/templates/Common.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.17/templates/Proxy.gitlab-ci.yml
  - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.5.17/templates/Stages.gitlab-ci.yml

workflow:
  rules:
    - when: always

# @Description parallel to build images
docker_build:
  extends:
    - .devcontainer::build
    - .proxy_backend
  stage: container-build
  parallel:
    matrix:
      - IMAGE: $BUILD_IMAGE_LIST
  variables:
    IMAGE_NAME: msclock/$IMAGE:$TAG_TO_IMAGE
    WORKING_DIRECTORY: images/$IMAGE
    PUSH: '1'
    PIN_LATEST: '1'
