# Job to lint a .pageanrc.json file.

lint_pageanrc:
  image: registry.gitlab.com/gitlab-ci-utils/pagean:10.0.0@sha256:d875c0a7c02c60f886f14b7a1ab839c4e4e50e527987f22aa3f57bc53fd94504
  stage: lint
  variables:
    PAGEANRC_FILE: .pageanrc.json
  needs: []
  script:
    - pageanrc-lint $PAGEANRC_FILE
